### ISSUE TITLE
jQuery error when selecting file from pop up in admin: Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by swaterfall** [django-cms/django-filer#1133]
I'm getting a jquery error when trying to select a file from admin:

`Uncaught TypeError: $ is not a function at window.dismissRelatedImageLookupPopup (popup_handling.js:18) at HTMLAnchorElement.onclick (?_pick=file&_popup=1:412)`

Using 1.4.4 and Django 2.1.7

**Comment by Arussil** [comment]
I also got this error, but only with a model that use FilerFileField, seems like Django jQuery is loaded after the dropzone and widget JS.

**Comment by mpwoodward** [comment]
I'm getting this error with FilerImageField as well -- Django 2.1.7 and Filer 1.4.4.

**Comment by debaze** [comment]
> seems like Django jQuery is loaded after the dropzone and widget JS.

I got the same problem. Seems to be solved by adding jquery and init script explicitly on top of the admin template, and add the jquery and init scripts as static files. However this feels very hacky, so a better fix would be appreciated!

`templates/admin/base.html`

    {% extends 'admin/base.html' %}
      {% block extrahead %}
          <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
          <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
      {% endblock %}

**Comment by bclermont** [comment]
Got same problem, ends up downgrading to Django 1.11.x

**Comment by matthiask** [comment]
I did some work on media merging in Django because I also encountered problems where assets were ordered incorrectly. Django 2.2 fixes this for good but also makes it necessary to explicitly depend on django.jQuery. See

Release notes:
https://docs.djangoproject.com/en/2.2/releases/2.2/#merging-of-form-media-assets
Possible fix:
https://github.com/matthiask/django-cabinet/commit/f183dcb4db382ccb1ba9fe1e328695c1d7181709

**Comment by adrien-delhorme** [comment]
See PR: #1116
