### ISSUE TITLE
Drag & drop of empty files results into Internal Server Error

### ISSUE THREAD

**Issue by barsch** [django-cms/django-filer#1232]
If I use the upload button a nifty little javascript popup says "test.txt is empty, please select files again without it." - however using drag & drop displays a not very useful error message "test.txt: [object Object]" in the backend and raises a Internal Server Error without any traceback in the console.

![error](https://user-images.githubusercontent.com/602450/103620950-b47e4580-4f34-11eb-9395-63bbdb553876.png)

**Comment by jrief** [comment]
This actually happens because you didn't set `allow_empty_files=True` on your Form.
Details here: https://docs.djangoproject.com/en/3.1/ref/forms/fields/#filefield

I agree that raising a 500 (Internal Server Error) is not the best return code, I therefore changed this to 422 (Unprocessable Entity). I also fixed the rendering of the error message. It now tells you that the file is empty.

**Comment by barsch** [comment]
I didn't use ```FileField```/```ImageField``` for the test above - this error came up for dragging an empty file into the Filer / Folders  backend itself.

**Comment by jrief** [comment]
OK, then this is the default setting in django-filer. The question is, if we shall allow empty files or not. I will ask this on the developers Slack channel.

Fell free to join at https://django-cmsworkspace.slack.com/archives/C01DX920K60
