### ISSUE TITLE
[bug] Unable to use v2.2 when group admin is disabled

### ISSUE THREAD

**Issue by petrklus** [django-cms/django-filer#1291]
A project where group management is disabled, for example via:

    admin.site.unregister(Group)
    
Is unable to use Filer, as the PermissionAdmin now contains a reference to 'group' under `autocomplete_fields`:

https://github.com/django-cms/django-filer/blob/master/filer/admin/permissionadmin.py#L16

Suggestions?

**Comment by marksweb** [comment]
@petrklus As it stands, django's groups are a requirement of the project due to this admin class getting loaded by default.

There is a config option for permissions; https://django-filer.readthedocs.io/en/latest/permissions.html#permissions

Perhaps there should be checks in place for the `FILER_ENABLE_PERMISSIONS` setting to optionally import the permissions side of the app so that you can use it in a configuration such as yours.

**Comment by FinemechanicPub** [comment]
I have a similar issue. I'm using my own group class inherited from Group and it has a different name, so django-filer stops with the error stating that the Group model is not registered.

**Comment by linhvng** [comment]
> I have a similar issue. I'm using my own group class inherited from Group and it has a different name, so django-filer stops with the error stating that the Group model is not registered.

I have the same issue as well
