### ISSUE TITLE
Saved image cannot be displayed

### ISSUE THREAD

**Issue by kevinxpfeiffer** [django-cms/django-filer#1299]
I'm having a problem viewing uploaded images.
The images can be uploaded without any problems and will also be saved in the specified folder.
After that it will be shown as follows:
<img width="1353" alt="Screenshot 2022-07-16 at 17 11 57" src="https://user-images.githubusercontent.com/84971615/179361013-aec94e4d-52d4-46f7-8787-4d0bfc456b24.png">
When I then click on expand I get the following error:
<img width="1512" alt="Screenshot 2022-07-16 at 17 12 18" src="https://user-images.githubusercontent.com/84971615/179361016-fced735b-f5fe-488d-b8ea-abfb0b0249ce.png">
I installed django-filer according to the documentation. But apparently it doesn't work.

How can I solve this problem?

**Comment by marksweb** [comment]
@pfeiffer-dev What versions of django & django-filer are you using?

I've no issue with a project using django 3.2 and django-filer 2.2.1

**Comment by xpfeiffer** [comment]
@marksweb thank you for your interest. 
I'm currently using Django 3.2.14 and django-filer 2.2.1.

**Comment by Milutinke92** [comment]
@marksweb  Hi, I have a similar issue.

On admin folder page, i see all images, and I can upload new ones, then, when I select one image, I see it in model field.
But, when I save, and page is reload, I get the `file-missing.svg` displayed.

When I debug, I got that `{% if object.file.exists %}` in `admin_file.html` returns `false`. 

So I am confused, on Admin File Folder, it's using local paths, and for checking if file exists, uses storage, (which in our case is S3) and that's why returns false (on local development, everything works as it should).

Some suggestions?
