### ISSUE TITLE
Dragging Folders into Folders in Admin does not work

### ISSUE THREAD

**Issue by alexgustafson** [django-cms/django-filer#1403]
When a user tries to move a folder into another folder the UI suggests that it would be possible but nothing happens after the drag event. No request is sent to the sever.

I am aware of the "Move files and/or folders" button in the admin, that is working fine. I think the drag and drop functionality should work for folder as well, or the UI should indicate that this is not possible.

Am I missing some configuration option? or is this a bug?

I am using the following:

Django==4.1.7
django-cms==3.11.3
django-filter==3.0.3

**Comment by jrief** [comment]
I'm currently rewriting django-filer in order to get rid of all that legacy JavaScript code. Nobody is able to maintain that code without major headaches. I wrote a [proposal](https://github.com/django-cms/django-filer/discussions/1348) some time ago.

Instead I use TypeScript with React using the [DnD-Kit](https://docs.dndkit.com/). The folder view then will behave more like we know it from Windows Explorer or Mac's Finder. Please wait a few weeks until I have a presentable prototype.

If you want to help, please provide icons in SVG. Filer currently uses [small-n-flat](http://paomedia.github.io/small-n-flat/) icons. If you know of a more complete library, please let me know. Otherwise, I would need an icon for a non-empty folder. Maybe someone can create a folder icon using the provided folder and add some stuff to make it look filled.

**Comment by jrief** [comment]
@alexgustafson the working draft of the new django-filer implements this feature. Please check here for details:
https://github.com/django-cms/django-filer/blob/poc-finder/README-Finder.md
