### ISSUE TITLE
How to add support for markdown file on drag and drop

### ISSUE THREAD

**Issue by fanto88** [django-cms/django-filer#1432]
When i try to upload a .md file using the drag and drop feature i get this error:

![image](https://github.com/django-cms/django-filer/assets/10716240/2aecadf2-2c4f-459d-9e05-39b5d6f511ea)

While if i upload using the button 'upload file' i don't get any problem at all and the single file is correctly uploaded

django-filer==2.0.2
Django==3.1.14

**Comment by fsbraun** [comment]
@fanto88 Thanks for reporting this. 

I've just tested with django-filer==3.1.0 and the drag and drop of markdown files works fine. It seems to have been fixed somewhere since 2.0.2. Upgrading django-filer might be the easiest option. The first version this bug is fixed is 2.1. Since an upgrade needs migrations to run you might consider going to 3.1 directly.

**Comment by fanto88** [comment]
> @fanto88 Thanks for reporting this.
> 
> I've just tested with django-filer==3.1.0 and the drag and drop of markdown files works fine. It seems to have been fixed since 2.0.2. Upgrading django-filer might be the easiest option. The first version, this bug is fixed, is 2.1. Since an upgrade to 2.1 needs migrations to run, you might consider going to 3.1 directly.

Thanks for the quick test. From what I see version 3.X requires django 3.2, but for now I can't upgrade the django version. I will try to find the latest version supported by django 3.1 and upgrade to it, hoping to fix the problem.

**Comment by fsbraun** [comment]
Start with 2.1?

**Comment by fanto88** [comment]
Thanks for the tips, everything seems to work fine right now.
