### ISSUE TITLE
update installation docs

### ISSUE THREAD

**Issue by stefanfoulis** [django-cms/django-filer#268]
go through the setup process for a fresh project (django-admin.py createproject) und update the docs to reflect all needed steps.

e.g:
- settings `MEDIA_URL` and `MEDIA_ROOT` and `STATIC_`
- ...

**Comment by dvarrazzo** [comment]
I confirm such need.

I've spent some quality time before understanding that if `MEDIA_URL` is not set the file urls will be broken: they will be relative from current page, so from admin they will look like `http://DOMAIN/filer/file/1/change/filer_public/HASH/FILENAME` instead of ``http://DOMAIN/filer_public/HASH/FILENAME``, which will result in a redirect appending `/`, then appending `/change/` then 404.
