### ISSUE TITLE
UPLOAD_TO_PREFIX leaks into thumbnail path

### ISSUE THREAD

**Issue by evildmp** [django-cms/django-filer#397]
Say you have something like:

```
FILER_STORAGES = {
    'public': {
        'main': {
            'ENGINE': 'filer.storage.PublicFileSystemStorage',
            'OPTIONS': {},
            'UPLOAD_TO': 'filer.utils.generate_filename.by_date',
            'UPLOAD_TO_PREFIX': 'yabbadabbadoo',
        },
        'thumbnails': {
            'ENGINE': 'filer.storage.PublicFileSystemStorage',
            'OPTIONS': {},
            'THUMBNAIL_OPTIONS': {
                'base_dir': 'filer_public_thumbnails',
            },
        },
    },
}
```

You'll find that thumbnails are generated in `media/filer_public_thumbnails/yabbadabbadoo/date/path/to/item`. 

Is it intended that `UPLOAD_TO_PREFIX` should be in that path? It seems odd to me.

**Comment by wiesson** [comment]
Any updates to this?

**Comment by stefanfoulis** [comment]
this is by design, as the original will be saved in the database as ``yabbadabbadoo/..../myfile.jpg`` and the thumbnail backend just adds the thumnailing options to the filename and saves in the other storage.

To change this, the resulting thumbnail path would have to be post-processed after easy-thumbnails does its thing.
