### ISSUE TITLE
thumbnail background on preview

### ISSUE THREAD

**Issue by darioalbanesi** [django-cms/django-filer#562]
When using images with a white logo on a transparent background, it is not possible to recognise the image on the filer thumbnail preview. A checkerboard background would solve the problem.

![Checkerboard Background](http://informationworker.ru/snagit10.en/images/checkerboard.png)

**Comment by strindhaug** [comment]
I had the same problem and I've created a fix for this (noticed this issue when I was about to create the commit). 

Since I often find that the classical pattern with fairly large squares as in your example a bit distracting (it makes transparent gray images look jagged), I used a fairly light checkerboard pattern with small squares (4x4 px squares). To be able to see light transparent images properly it changes to a black and dark gray pattern when hovering the cursor.

**Comment by lory87** [comment]
gentle ping @strindhaug Is this issue fixed for you in current filer version 1.2.0 so we can close?

**Comment by strindhaug** [comment]
@lory87 sure!  :+1:
