### ISSUE TITLE
django-suit integration broken

### ISSUE THREAD

**Issue by qari** [django-cms/django-filer#775]
`TemplateDoesNotExist at /admin/filer/folder/unfiled_images/
admin/filer/tools/upload_button_js.html
Request Method: GET
Request URL:    http://127.0.0.1:8000/admin/filer/folder/unfiled_images/
Django Version: 1.9
Exception Type: TemplateDoesNotExist
Exception Value:    
admin/filer/tools/upload_button_js.html`

**Comment by stefanfoulis** [comment]
thanks for reporting @qari

**Comment by qari** [comment]
You have this problem on Django 1.9.*  and last version suit?

**Comment by oesah** [comment]
have the same issue. Running Django 1.9.4.

**Comment by stefanfoulis** [comment]
@qari @oesah do you experience this problem with ``django-filer==1.1.1`` or the ``develop`` branch as well?

**Comment by ycuk** [comment]
I have the same issue.
Django==1.9.4
django-filer==1.1.1
django-suit==0.2.18

TemplateDoesNotExist: admin/filer/tools/upload_button_js.html

I have take a look at 'site-packages/filer' and there isnt file upload_button_js.html anywhere

**Comment by stefanfoulis** [comment]
@ycuk @qari @oesah  I'm pretty sure this is fixed on the develop branch. If possible, could you please confirm that you're not experiencing the issue on develop anymore.

We plan to release asap, but we're a bit low on frontend devs this week and we still have some open issues (https://github.com/divio/django-filer/milestones/1.2.0). As soon as those are fixed and we've gone through QA, we'll release to pypi.

**Comment by ycuk** [comment]
@stefanfoulis nope. still the same problem on the develop branch. 

> In template /Users/ycuk/envs/zxc/lib/python2.7/site-packages/suit/templates/admin/filer/folder/directory_listing.html, error at line 72

**Comment by stefanfoulis** [comment]
@ycuk ah, I see. This is a problem with the django-filer support in suit. We changed our template structure and django-suit is still assuming the old.
It looks like there are a lot of templates from filer overridden here: https://github.com/darklow/django-suit/tree/develop/suit/templates/admin/filer

There already is an Issue filed there: darklow/django-suit#484

The tricky thing will be to include different versions of the templates for django-filer and conditionally use them. Or django-suit can update the filer templates in django-suit and just declare that django-filer>=1.2 is required.

I changed the title of the issue to match the actual problem, since it needs to be fixed in django-suit.

**Comment by stefanfoulis** [comment]
I'm keeping this Issue open here as a reference to the issue in django-suit.

**Comment by davidkrcil** [comment]
Is there any solution to it today?

**Comment by valych** [comment]
@davidkrcil as mentioned here darklow/django-suit#484, you can use some hack and put `filer` above the `suit` in `INSTALLED_APPS`

**Comment by dennisvd** [comment]
Has this issue with Django suit been resolved.
I see the same error with Django 1.9.13 and django-suit 0.2.28

In the process of upgrading the Django release.

Does this issue remain for Django 1.9+ releases?
