### ISSUE TITLE
Download counter with Django-Filer

### ISSUE THREAD

**Issue by maltebeckmann** [django-cms/django-filer#841]
Would there be an easy way to count the number of times a Django-Filer file is downloaded?

**Comment by vstoykov** [comment]
1. You need to create extra model that will store that information and view that will serve the files and increase the counter.
2. You need to configure your web server not to serve the files under `filer_public` folder and instead to pass the request to Django in order your custom view to be able to serve the file.
3. (Almost required) Because it's not a good idea Django to serve files in production your custom view probably need to leverage `django-sendfile` (https://pypi.python.org/pypi/django-sendfile) or similar approach of serving these files.

**Comment by yakky** [comment]
@maltebeckmann I'm sorry because source code is in italian, but you can have a look at this https://github.com/CroceRossaItaliana/jorvik/blob/master/gestione_file/viste.py#L86 for an implementation of a download counter
