### ISSUE TITLE
Any reason filer doesn't store files in original structure?

### ISSUE THREAD

**Issue by wyx2000** [django-cms/django-filer#872]
if I have files like
/test.html
/css/test.css
/images/test.png
why filer need store them in path like 
filer_public/34/65/34658372-ec78-4df0-9ddb-4d48c3231d44/test.html
when store files like this, it is hard to serve them on http. I could not find a way to serve file content while parse the request url. I first tried "serve" in "django.views.static", it worked, but it is not recommended to be used in production, and it doesn't support SSL well.

**Comment by vstoykov** [comment]
You just need to tell your webserver to serve everything under `MEDIA_URL` from `MEDIA_ROOT`. Normally `filer_public` is inside `MEDIA_ROOT` and you will not have any problems with serving them.

If you like to set the exact path from where your file will be served this is another story. Normally when you use it you don't care about the URL and most importantly you do not upload CSS or HTML files from `django-filer`.

More info about media files in Django here https://docs.djangoproject.com/en/1.9/topics/files/

**Comment by yakky** [comment]
Since filer 1.1 (IIRC) you can used file canonical url https://django-filer.readthedocs.io/en/latest/installation.html#canonical-urls to serve files using a constant path. filer also support sendfile extensions to offload the files serving to the webserver

**Comment by benzkji** [comment]
Canonical URLs look great, but there is a lot more additional configuration (offloading server, is this similar to the process here: https://django-filer.readthedocs.io/en/latest/secure_downloads.html#secure-downloads ?).

In one project, I used this, removing all that hashes: https://gist.github.com/benzkji/5f14fef05021f325c7ef
And proposed, but had no time for writing tests :( https://github.com/divio/django-filer/issues/543 ) But, canonical URLs are still better, because the URLs really remain the same.
