### ISSUE TITLE
Search input overlays tool icons in folder view

### ISSUE THREAD

**Issue by trawick** [django-cms/django-filer#956]
I'm seeing some misformatting when loading a folder in django-filer.  (Versions tested: 1.2.5 and 1.26, with Django 1.8.17.) The input box for searching (filtering) overlays some of the toolbar.

Initial view in Chrome 56.0.2924.87 on Ubuntu after loading /admin/filer/folder:

![image](https://cloud.githubusercontent.com/assets/1207350/22551432/c8c3f4e4-e922-11e6-8b67-60b8fccff322.png)

After clicking in the search input:

![image](https://cloud.githubusercontent.com/assets/1207350/22551460/e91f5580-e922-11e6-8720-0d9f939416b5.png)

Initial view in Firefox 51.0.1 on Ubuntu:

![image](https://cloud.githubusercontent.com/assets/1207350/22551507/0282d240-e923-11e6-8c5a-4d6f58c82bb9.png)

Going through the elements around the problem in developer tools on Chrome and Firefox, I don't see any styles coming from my project's stylesheets.  I see _filter-files.scss, _navigator.scss, and Django's django/contrib/admin/static/admin/css/base.css.

Is anyone else seeing this glitch?  If not, does anyone have hints for better isolating the problem?

Thanks!

**Comment by plp13** [comment]
This affects me, as well.

**Comment by trawick** [comment]
Thanks for confirming; I wasn't sure how to absolutely rule out my project!

**Comment by plp13** [comment]
Now all we have to do is fix it. :-)

BTW, take a look a this:
http://stackoverflow.com/questions/38922116/django-filer-renders-incorrectly-in-admin-site

It looks like someone has suggested a workaround for this problem: install djangocms-admin-style.

Trouble is, I can't do that because a) I don't like the way it looks, and b) it clashes with django-admin-tools which I'm already using for my project.

**Comment by plp13** [comment]
I made some progress fixing this issue by editing admin_filer.css (I didn't bother with the Sass). The problem seems to lie with the width of class .filter-files-container being too small, together with a 'float: left' of .filter-files-container .filter-search-wrapper.

Here's the modified admin_filter.css, if you want to take a look:
https://gist.github.com/plp13/4e37dc613fb886a0840c76add4c6d278

Modified lines are marked as /* changed */ and deleted lines are commented out.

Please note that, although these changes appear to work with *my* project with both Firefox and Chrome, there's not guarantee they'll work for you. (I'm using Django 1.9.6, django-admin-tools 0.7.2, and no CMS.) Also, the file includes a few other cosmetic changes that are unrelated to this issue (basically, a colour scheme that matches the look of Django's classic admin).

**Comment by trawick** [comment]
The modified admin_filter.css works for me.  Thanks for your effort!

**Comment by plp13** [comment]
It still has issues. For example, when you open it in a popup window in Firefox.

Anyway, I decided to go with the 'nuclear option' and roll my own file browser. It's not really difficult to do, and I also prefer code that doesn't rely on CSS other than that of django.contrib.admin.

**Comment by Nomados** [comment]
jango 1.11 has the same trouble. Please fix it! the other stuff is wonderful.

**Comment by raeuz** [comment]
filer 1.5.0 with django 2.2

same issue in Chrome & Firefox
